version: "2"

run:
  timeout: 5m

linters:
  enable:
    - bodyclose
    - contextcheck
    - errcheck
    - errorlint
    - govet
    - ineffassign
    - nilerr
    - noctx
    - revive
    - staticcheck
    - unused
